## NodeJS Unimed - Busybox - rodando no ambiente de desenvolvimento
# Este projeto é voltado para testes unistário em estágios do CI;

image: harbor.unimednatal.com.br/busybox-nodejs/${DOCKER_USERNAME}/${APPLICATION_NAME}:${IMAGE_TAG}

stages:
    - clone
    - build
    - test
    - push
    - deploy
    - logs
    - deploy_review

clone:
    stage: clone
    tags:
        - node-busy
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/; rm -rf nodejs-busybox
        - cd /home/gitlab-runner/projetos/; git clone -b docker/nodejsbusybox https://devopsunimed:glpat-PreJFT3SnriFSMAHFouu@gitlab.com/unimed_natal/devops/nodejs-busybox.git nodejs-busybox
        #clonando o repositório para dentro do host apartir de uma branch específica

build:
    stage: build
    tags:
        - node-busy
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/nodejs-busybox; make build tag
        #buildando uma nova imagem docker e tagueando como "latest"  
    needs: ["clone"]
    
test:
    stage: test
    tags:
        - node-busy
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/nodejs-busybox; make test
        #enviando a nova imagem ao repositório do harbor
    needs: ["clone", "build"]

push:
    stage: push
    tags:
        - node-busy
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/nodejs-busybox; make push
        #enviando a nova imagem ao repositório do harbor
    needs: ["clone", "build", "test"]

deploy:
    stage: deploy
    tags:
        - node-busy
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/nodejs-busybox; docker compose up -d
        #fazendo deployment da stack em docker swarm, através do compose file;
    needs: ["clone", "build", "test", "push"]

logs:
    stage: logs
    tags:
        - node-busy
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/nodejs-busybox; make test
    needs: ["clone", "build", "test","push","deploy"]

deploy_review:
  stage: deploy_review
  script:
    - echo "Add script here that deploys the code to your infrastructure"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://10.10.36.21:3015/
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" 