## NodeJS Unimed - Busybox - rodando no ambiente de desenvolvimento
# Este projeto é voltado para testes unistário em estágios do CI;

image: harbor.unimednatal.com.br/busybox-nodejs/${DOCKER_USERNAME}/${APPLICATION_NAME}:${IMAGE_TAG}

stages:
    - clone
    - build
    - test
    - push
    - deploy
    - logs

clone:
    stage: clone
    tags:
        - node-busy
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/; rm -rf nodejs-busybox
        - cd /home/gitlab-runner/projetos/; git clone -b docker/nodejsbusybox https://devopsunimed:glpat-PreJFT3SnriFSMAHFouu@gitlab.com/unimed_natal/devops/nodejs-busybox.git nodejs-busybox
        #clonando o repositório para dentro do host apartir de uma branch específica
    environment:
      name: staging
      url: http://10.10.36.21:3015/

build:
    stage: build
    tags:
        - node-busy
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/nodejs-busybox; make build tag
        #buildando uma nova imagem docker e tagueando como "latest"
    environment:
      name: staging
      url: http://10.10.36.21:3015/    
    needs: ["clone"]
    

test:
    stage: test
    tags:
        - node-busy
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/nodejs-busybox; make test
        #enviando a nova imagem ao repositório do harbor
    environment:
      name: staging
      url: http://10.10.36.21:3015/
    needs: ["clone", "build"]

push:
    stage: push
    tags:
        - node-busy
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/nodejs-busybox; make push
        #enviando a nova imagem ao repositório do harbor
    environment:
      name: staging
      url: http://10.10.36.21:3015/
    needs: ["clone", "build", "test"]

deploy:
    stage: deploy
    tags:
        - node-busy
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/nodejs-busybox; docker compose up -d
        #fazendo deployment da stack em docker swarm, através do compose file;
    environment:
      name: staging
      url: http://10.10.36.21:3015/
    needs: ["clone", "build", "test", "push"]

logs:
    stage: logs
    tags:
        - node-busy
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/unimed/Ansible-Projects/ansible-playbooks; ansible-playbook docker_logs.yaml -u unimed -i hosts
    environment:
      name: staging
      url: http://10.10.36.21:3015/
    needs: ["clone", "build", "test","push","deploy"]