## NodeJS Unimed - Busybox - rodando no ambiente de desenvolvimento
# Este projeto é voltado para testes unistário em estágios do CI;

image: unimed/node-busybox:2.0

stages:
    - clone
    - build
    - test
    - push
    - deploy
    - logs

clone:
    stage: clone
    tags:
        - nodejs-busybox
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/; rm -rf nodejs-busybox
        - cd /home/gitlab-runner/projetos/; git clone -b docker/nodejsbusybox https://thanos:1A1e64xqYMJiL3AeVHpd@gitlab.unimednatal.com.br/devops_group/nodejs-busybox.git nodejs-busybox
        #clonando o repositório para dentro do host apartir de uma branch específica

build:
    stage: build
    tags:
        - nodejs-busybox
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/nodejs-busybox; make build tag
        #buildando uma nova imagem docker e tagueando como "latest"
    needs: ["clone"]

test:
    stage: test
    tags:
        - nodejs-busybox
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/nodejs-busybox; make test
        #enviando a nova imagem ao repositório do harbor
    needs: ["clone", "build"]

push:
    stage: push
    tags:
        - nodejs-busybox
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/nodejs-busybox; make push
        #enviando a nova imagem ao repositório do harbor
    needs: ["clone", "build", "test"]

deploy:
    stage: deploy
    tags:
        - nodejs-busybox
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/gitlab-runner/projetos/nodejs-busybox; docker compose up -d
        #fazendo deployment da stack em docker swarm, através do compose file;
    needs: ["clone", "build", "test", "push"]

logs:
    stage: logs
    tags:
        - nodejs-busybox
    only:
        - docker/nodejsbusybox
    script:
        - cd /home/unimed/Ansible-Projects/ansible-playbooks; ansible-playbook docker_logs.yaml -u unimed -i hosts
    needs: ["clone", "build", "test","push","deploy"]
