#Imagem de Busy Box, com o objetivo de rodar testes de CI e best pratices docker,
#Node: latest | Bash: latest
#Repositório: 
version: '3'
services:
  nodejs-busybox-test:
    env_file:
      - .env
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    container_name: nodejs-busybox-test
    image: harbor.unimednatal.com.br/busybox-nodejs/${DOCKER_USERNAME}/${APPLICATION_NAME}:${IMAGE_TAG}
    ports:
      - '3080:3000'
    volumes:
      - .:/opt/app
    command: bash -c "npm run start:dev"
    restart: always
    network_mode: bridge