#Imagem de Busy Box, com o objetivo de rodar testes de CI e best pratices docker,
#Node: latest | Bash: latest
#Repositório: 
version: '2'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: unimed/node-busybox:2.0
    command: bash -c "npm run start:dev"
    container_name: nodejs-busybox
    volumes:
      - .:/opt/app
    ports:
      - 3000
    restart: always
    network_mode: bridge
