#Playbook para rodar no ambiente Docker de DESENVOLVIMENTO
#Versão 1.0 - BETA
---
- hosts: all

  tasks:
    - ping: ~

    - name: Removendo Imagens Docker não utilizadas
      become: true
      become_method: su
      become_user: unimed
      docker_prune:
        images: yes
        images_filters:
          dangling: false
    
    - name: Removendo Containers, Networks e Volumes não utilizados
      docker_prune:
        containers: yes
        networks: yes
        volumes: yes
        builder_cache: yes
