apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.26.1 (a9d05d509)
    namespace: node-busybox
  creationTimestamp: null
  labels:
    io.kompose.service: node-busybox
  name: node-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-busybox
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: node-busybox
    spec:
      restartPolicy: Always
      containers:
        - args:
            - npm 
            - run
            - dev 
          name: node-busybox
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }} 
          imagePullPolicy: Always        
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: 1Gi
              cpu: 800m
            requests:
              memory: 648Mi        
              cpu: 400m
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 10
          readinessProbe:
            httpGet: 
              path: /
              port: 3000
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          securityContext:
            capabilities: {}
            readOnlyRootFilesystem: false
          volumeMounts:
          - mountPath: /opt/app
            name: app
          #- mountPath: /home/node/app/vendor
            #name: vendor
      volumes:
        - hostPath:
            path: /home/gitlab-runner/builds/glrt-8JP/1/unimed_natal/devops/nodejs-busybox
            type: DirectoryOrCreate
          name: app
        #- hostPath:
            #path: /home/unimed/projetos/api-servicos/vendor
            #type: DirectoryOrCreate
          #name: vendor
status: {}